[package]
name = "parkpull"
version = "0.1.0"
authors = ["Kyle Laker <kyle@laker.email>"]
edition = "2018"

[dependencies]
chrono = "~0.4"
reqwest = "~0.9"
serde = "~1.0"
serde_derive = "~1.0"
serde_yaml = "~0.8"
